### ISSUE TITLE
Can you put an api for cloud storage of class with s3?

### ISSUE THREAD

**Issue by hamedasgari88** [SkyroomOnline/webservice#3]

**Comment by mkhahani** [comment]
What do you expect from that API? Please explain.

**Comment by hamedasgari88** [comment]
How to save an online meeting on the cloud
Information such as sounds, videos, chats and all events?
Like Adobe Connect
Thank

**Comment by mkhahani** [comment]
Sorry, we have not implemented server side recording yet.
